class GatewayConfig:
    NAME = 'name'
    TYPE = 'type'
    GATEWAY_IB = 'interactive_broker'
    GATEWAY_CQG = 'cqg'
    HOST = 'host'
    PORT = 'port'
    USER = 'user'
    PASSWORD = 'password'
    APP_ID = 'app_id'
    VERSION = 'version'
    PRIVATE_LABEL = 'private_label'
    ACCOUNT_ID = 'account_id'
    CLIENT_ID = 'client_id'
    RECONNECT_MAX_RETRY = 'reconnect_max_retry'
    RECONNECT_INTERVAL = 'reconnect_interval_in_sec'
    STATE_FILE_PATH = 'state_file_path'
