# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebAPI/account_authorization_2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..common import shared_1_pb2 as common_dot_shared__1__pb2
from ..common import timestamp_pb2 as common_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WebAPI/account_authorization_2.proto',
  package='account_authorization_2',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$WebAPI/account_authorization_2.proto\x12\x17\x61\x63\x63ount_authorization_2\x1a\x15\x63ommon/shared_1.proto\x1a\x16\x63ommon/timestamp.proto\"F\n\x0c\x41\x63\x63ountLogon\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x10\n\x08username\x18\x02 \x02(\t\x12\x10\n\x08password\x18\x03 \x02(\t\"\xaa\x02\n\x12\x41\x63\x63ountLogonResult\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12$\n\x0ctext_message\x18\x03 \x01(\x0b\x32\x0e.shared_1.Text\x12\x38\n\x14server_utc_timestamp\x18\x04 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8a\x01\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12(\n$RESULT_CODE_PASSWORD_CHANGE_REQUIRED\x10\x01\x12 \n\x1cRESULT_CODE_PASSWORD_EXPIRED\x10\x02\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65\"W\n\x15\x41\x63\x63ountPasswordChange\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x14\n\x0cold_password\x18\x02 \x02(\t\x12\x14\n\x0cnew_password\x18\x03 \x02(\t\"\xac\x01\n\x1b\x41\x63\x63ountPasswordChangeResult\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12$\n\x0ctext_message\x18\x03 \x01(\x0b\x32\x0e.shared_1.Text\">\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65\"#\n\rAccountLogoff\x12\x12\n\naccount_id\x18\x01 \x02(\x11\"\xde\x01\n\x13\x41\x63\x63ountLogoffResult\x12\x12\n\naccount_id\x18\x01 \x02(\x11\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12$\n\x0ctext_message\x18\x03 \x01(\x0b\x32\x0e.shared_1.Text\x12\x38\n\x14server_utc_timestamp\x18\x04 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\">\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65'
  ,
  dependencies=[common_dot_shared__1__pb2.DESCRIPTOR,common_dot_timestamp__pb2.DESCRIPTOR,])



_ACCOUNTLOGONRESULT_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='account_authorization_2.AccountLogonResult.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_PASSWORD_CHANGE_REQUIRED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_PASSWORD_EXPIRED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_FAILURE', index=3, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=345,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTLOGONRESULT_RESULTCODE)

_ACCOUNTPASSWORDCHANGERESULT_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='account_authorization_2.AccountPasswordChangeResult.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_FAILURE', index=1, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=685,
  serialized_end=747,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTPASSWORDCHANGERESULT_RESULTCODE)

_ACCOUNTLOGOFFRESULT_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='account_authorization_2.AccountLogoffResult.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_FAILURE', index=1, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=685,
  serialized_end=747,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTLOGOFFRESULT_RESULTCODE)


_ACCOUNTLOGON = _descriptor.Descriptor(
  name='AccountLogon',
  full_name='account_authorization_2.AccountLogon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='account_authorization_2.AccountLogon.account_id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='account_authorization_2.AccountLogon.username', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='account_authorization_2.AccountLogon.password', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=182,
)


_ACCOUNTLOGONRESULT = _descriptor.Descriptor(
  name='AccountLogonResult',
  full_name='account_authorization_2.AccountLogonResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='account_authorization_2.AccountLogonResult.account_id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='account_authorization_2.AccountLogonResult.result_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_message', full_name='account_authorization_2.AccountLogonResult.text_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_utc_timestamp', full_name='account_authorization_2.AccountLogonResult.server_utc_timestamp', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCOUNTLOGONRESULT_RESULTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=483,
)


_ACCOUNTPASSWORDCHANGE = _descriptor.Descriptor(
  name='AccountPasswordChange',
  full_name='account_authorization_2.AccountPasswordChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='account_authorization_2.AccountPasswordChange.account_id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='old_password', full_name='account_authorization_2.AccountPasswordChange.old_password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_password', full_name='account_authorization_2.AccountPasswordChange.new_password', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=572,
)


_ACCOUNTPASSWORDCHANGERESULT = _descriptor.Descriptor(
  name='AccountPasswordChangeResult',
  full_name='account_authorization_2.AccountPasswordChangeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='account_authorization_2.AccountPasswordChangeResult.account_id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='account_authorization_2.AccountPasswordChangeResult.result_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_message', full_name='account_authorization_2.AccountPasswordChangeResult.text_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCOUNTPASSWORDCHANGERESULT_RESULTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=747,
)


_ACCOUNTLOGOFF = _descriptor.Descriptor(
  name='AccountLogoff',
  full_name='account_authorization_2.AccountLogoff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='account_authorization_2.AccountLogoff.account_id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=749,
  serialized_end=784,
)


_ACCOUNTLOGOFFRESULT = _descriptor.Descriptor(
  name='AccountLogoffResult',
  full_name='account_authorization_2.AccountLogoffResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='account_authorization_2.AccountLogoffResult.account_id', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='account_authorization_2.AccountLogoffResult.result_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_message', full_name='account_authorization_2.AccountLogoffResult.text_message', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_utc_timestamp', full_name='account_authorization_2.AccountLogoffResult.server_utc_timestamp', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCOUNTLOGOFFRESULT_RESULTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=1009,
)

_ACCOUNTLOGONRESULT.fields_by_name['text_message'].message_type = common_dot_shared__1__pb2._TEXT
_ACCOUNTLOGONRESULT.fields_by_name['server_utc_timestamp'].message_type = common_dot_timestamp__pb2._TIMESTAMP
_ACCOUNTLOGONRESULT_RESULTCODE.containing_type = _ACCOUNTLOGONRESULT
_ACCOUNTPASSWORDCHANGERESULT.fields_by_name['text_message'].message_type = common_dot_shared__1__pb2._TEXT
_ACCOUNTPASSWORDCHANGERESULT_RESULTCODE.containing_type = _ACCOUNTPASSWORDCHANGERESULT
_ACCOUNTLOGOFFRESULT.fields_by_name['text_message'].message_type = common_dot_shared__1__pb2._TEXT
_ACCOUNTLOGOFFRESULT.fields_by_name['server_utc_timestamp'].message_type = common_dot_timestamp__pb2._TIMESTAMP
_ACCOUNTLOGOFFRESULT_RESULTCODE.containing_type = _ACCOUNTLOGOFFRESULT
DESCRIPTOR.message_types_by_name['AccountLogon'] = _ACCOUNTLOGON
DESCRIPTOR.message_types_by_name['AccountLogonResult'] = _ACCOUNTLOGONRESULT
DESCRIPTOR.message_types_by_name['AccountPasswordChange'] = _ACCOUNTPASSWORDCHANGE
DESCRIPTOR.message_types_by_name['AccountPasswordChangeResult'] = _ACCOUNTPASSWORDCHANGERESULT
DESCRIPTOR.message_types_by_name['AccountLogoff'] = _ACCOUNTLOGOFF
DESCRIPTOR.message_types_by_name['AccountLogoffResult'] = _ACCOUNTLOGOFFRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountLogon = _reflection.GeneratedProtocolMessageType('AccountLogon', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTLOGON,
  '__module__' : 'WebAPI.account_authorization_2_pb2'
  # @@protoc_insertion_point(class_scope:account_authorization_2.AccountLogon)
  })
_sym_db.RegisterMessage(AccountLogon)

AccountLogonResult = _reflection.GeneratedProtocolMessageType('AccountLogonResult', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTLOGONRESULT,
  '__module__' : 'WebAPI.account_authorization_2_pb2'
  # @@protoc_insertion_point(class_scope:account_authorization_2.AccountLogonResult)
  })
_sym_db.RegisterMessage(AccountLogonResult)

AccountPasswordChange = _reflection.GeneratedProtocolMessageType('AccountPasswordChange', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTPASSWORDCHANGE,
  '__module__' : 'WebAPI.account_authorization_2_pb2'
  # @@protoc_insertion_point(class_scope:account_authorization_2.AccountPasswordChange)
  })
_sym_db.RegisterMessage(AccountPasswordChange)

AccountPasswordChangeResult = _reflection.GeneratedProtocolMessageType('AccountPasswordChangeResult', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTPASSWORDCHANGERESULT,
  '__module__' : 'WebAPI.account_authorization_2_pb2'
  # @@protoc_insertion_point(class_scope:account_authorization_2.AccountPasswordChangeResult)
  })
_sym_db.RegisterMessage(AccountPasswordChangeResult)

AccountLogoff = _reflection.GeneratedProtocolMessageType('AccountLogoff', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTLOGOFF,
  '__module__' : 'WebAPI.account_authorization_2_pb2'
  # @@protoc_insertion_point(class_scope:account_authorization_2.AccountLogoff)
  })
_sym_db.RegisterMessage(AccountLogoff)

AccountLogoffResult = _reflection.GeneratedProtocolMessageType('AccountLogoffResult', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTLOGOFFRESULT,
  '__module__' : 'WebAPI.account_authorization_2_pb2'
  # @@protoc_insertion_point(class_scope:account_authorization_2.AccountLogoffResult)
  })
_sym_db.RegisterMessage(AccountLogoffResult)


# @@protoc_insertion_point(module_scope)
