# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebAPI/strategy_definition_2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WebAPI/strategy_definition_2.proto',
  package='strategy_definition_2',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"WebAPI/strategy_definition_2.proto\x12\x15strategy_definition_2\"\xfe\x02\n\x12StrategyDefinition\x12\x13\n\x0b\x61ggregation\x18\x01 \x01(\x08\x12\x42\n\x11\x65xchange_strategy\x18\x02 \x01(\x0b\x32\'.strategy_definition_2.ExchangeStrategy\x12\x11\n\ttick_size\x18\x03 \x01(\x01\x12\x14\n\x0cprice_offset\x18\x04 \x01(\x01\x12\x16\n\x0eround_leg_mode\x18\x05 \x01(\r\x12\x12\n\nnode_index\x18\x06 \x02(\r\x12G\n\x10node_definitions\x18\x07 \x03(\x0b\x32-.strategy_definition_2.StrategyNodeDefinition\x12\x18\n\x10user_description\x18\x08 \x01(\t\"W\n\x0cRoundLegMode\x12\x17\n\x13ROUND_LEG_MODE_DOWN\x10\x01\x12\x15\n\x11ROUND_LEG_MODE_UP\x10\x02\x12\x17\n\x13ROUND_LEG_MODE_MATH\x10\x03\"2\n\x10\x45xchangeStrategy\x12\x1e\n\x16\x65xchange_strategy_type\x18\x01 \x01(\t\"v\n\rLegDefinition\x12\x13\n\x0b\x63ontract_id\x18\x01 \x02(\r\x12\x12\n\nnode_index\x18\x02 \x02(\r\x12\x11\n\tqty_ratio\x18\x03 \x02(\x01\x12\x13\n\x0bprice_ratio\x18\x04 \x01(\x01\x12\x14\n\x0cprice_offset\x18\x05 \x01(\x01\"w\n\x0eNestedStrategy\x12=\n\ndefinition\x18\x01 \x02(\x0b\x32).strategy_definition_2.StrategyDefinition\x12\x11\n\tqty_ratio\x18\x02 \x01(\x01\x12\x13\n\x0bprice_ratio\x18\x03 \x01(\x01\"\xfc\x01\n\x16StrategyNodeDefinition\x12\x16\n\x0enode_operation\x18\x02 \x01(\r\x12\x31\n\x03leg\x18\x03 \x01(\x0b\x32$.strategy_definition_2.LegDefinition\x12>\n\x0fnested_strategy\x18\x04 \x01(\x0b\x32%.strategy_definition_2.NestedStrategy\"W\n\rNodeOperation\x12\x16\n\x12NODE_OPERATION_SUM\x10\x01\x12\x16\n\x12NODE_OPERATION_MUL\x10\x02\x12\x16\n\x12NODE_OPERATION_DIV\x10\x03'
)



_STRATEGYDEFINITION_ROUNDLEGMODE = _descriptor.EnumDescriptor(
  name='RoundLegMode',
  full_name='strategy_definition_2.StrategyDefinition.RoundLegMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROUND_LEG_MODE_DOWN', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROUND_LEG_MODE_UP', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROUND_LEG_MODE_MATH', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=444,
)
_sym_db.RegisterEnumDescriptor(_STRATEGYDEFINITION_ROUNDLEGMODE)

_STRATEGYNODEDEFINITION_NODEOPERATION = _descriptor.EnumDescriptor(
  name='NodeOperation',
  full_name='strategy_definition_2.StrategyNodeDefinition.NodeOperation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NODE_OPERATION_SUM', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NODE_OPERATION_MUL', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NODE_OPERATION_DIV', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=905,
  serialized_end=992,
)
_sym_db.RegisterEnumDescriptor(_STRATEGYNODEDEFINITION_NODEOPERATION)


_STRATEGYDEFINITION = _descriptor.Descriptor(
  name='StrategyDefinition',
  full_name='strategy_definition_2.StrategyDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aggregation', full_name='strategy_definition_2.StrategyDefinition.aggregation', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exchange_strategy', full_name='strategy_definition_2.StrategyDefinition.exchange_strategy', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tick_size', full_name='strategy_definition_2.StrategyDefinition.tick_size', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_offset', full_name='strategy_definition_2.StrategyDefinition.price_offset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round_leg_mode', full_name='strategy_definition_2.StrategyDefinition.round_leg_mode', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_index', full_name='strategy_definition_2.StrategyDefinition.node_index', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_definitions', full_name='strategy_definition_2.StrategyDefinition.node_definitions', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_description', full_name='strategy_definition_2.StrategyDefinition.user_description', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STRATEGYDEFINITION_ROUNDLEGMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=444,
)


_EXCHANGESTRATEGY = _descriptor.Descriptor(
  name='ExchangeStrategy',
  full_name='strategy_definition_2.ExchangeStrategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange_strategy_type', full_name='strategy_definition_2.ExchangeStrategy.exchange_strategy_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=496,
)


_LEGDEFINITION = _descriptor.Descriptor(
  name='LegDefinition',
  full_name='strategy_definition_2.LegDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_id', full_name='strategy_definition_2.LegDefinition.contract_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_index', full_name='strategy_definition_2.LegDefinition.node_index', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qty_ratio', full_name='strategy_definition_2.LegDefinition.qty_ratio', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_ratio', full_name='strategy_definition_2.LegDefinition.price_ratio', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_offset', full_name='strategy_definition_2.LegDefinition.price_offset', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=616,
)


_NESTEDSTRATEGY = _descriptor.Descriptor(
  name='NestedStrategy',
  full_name='strategy_definition_2.NestedStrategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='definition', full_name='strategy_definition_2.NestedStrategy.definition', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qty_ratio', full_name='strategy_definition_2.NestedStrategy.qty_ratio', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_ratio', full_name='strategy_definition_2.NestedStrategy.price_ratio', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=737,
)


_STRATEGYNODEDEFINITION = _descriptor.Descriptor(
  name='StrategyNodeDefinition',
  full_name='strategy_definition_2.StrategyNodeDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_operation', full_name='strategy_definition_2.StrategyNodeDefinition.node_operation', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leg', full_name='strategy_definition_2.StrategyNodeDefinition.leg', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nested_strategy', full_name='strategy_definition_2.StrategyNodeDefinition.nested_strategy', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STRATEGYNODEDEFINITION_NODEOPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=740,
  serialized_end=992,
)

_STRATEGYDEFINITION.fields_by_name['exchange_strategy'].message_type = _EXCHANGESTRATEGY
_STRATEGYDEFINITION.fields_by_name['node_definitions'].message_type = _STRATEGYNODEDEFINITION
_STRATEGYDEFINITION_ROUNDLEGMODE.containing_type = _STRATEGYDEFINITION
_NESTEDSTRATEGY.fields_by_name['definition'].message_type = _STRATEGYDEFINITION
_STRATEGYNODEDEFINITION.fields_by_name['leg'].message_type = _LEGDEFINITION
_STRATEGYNODEDEFINITION.fields_by_name['nested_strategy'].message_type = _NESTEDSTRATEGY
_STRATEGYNODEDEFINITION_NODEOPERATION.containing_type = _STRATEGYNODEDEFINITION
DESCRIPTOR.message_types_by_name['StrategyDefinition'] = _STRATEGYDEFINITION
DESCRIPTOR.message_types_by_name['ExchangeStrategy'] = _EXCHANGESTRATEGY
DESCRIPTOR.message_types_by_name['LegDefinition'] = _LEGDEFINITION
DESCRIPTOR.message_types_by_name['NestedStrategy'] = _NESTEDSTRATEGY
DESCRIPTOR.message_types_by_name['StrategyNodeDefinition'] = _STRATEGYNODEDEFINITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StrategyDefinition = _reflection.GeneratedProtocolMessageType('StrategyDefinition', (_message.Message,), {
  'DESCRIPTOR' : _STRATEGYDEFINITION,
  '__module__' : 'WebAPI.strategy_definition_2_pb2'
  # @@protoc_insertion_point(class_scope:strategy_definition_2.StrategyDefinition)
  })
_sym_db.RegisterMessage(StrategyDefinition)

ExchangeStrategy = _reflection.GeneratedProtocolMessageType('ExchangeStrategy', (_message.Message,), {
  'DESCRIPTOR' : _EXCHANGESTRATEGY,
  '__module__' : 'WebAPI.strategy_definition_2_pb2'
  # @@protoc_insertion_point(class_scope:strategy_definition_2.ExchangeStrategy)
  })
_sym_db.RegisterMessage(ExchangeStrategy)

LegDefinition = _reflection.GeneratedProtocolMessageType('LegDefinition', (_message.Message,), {
  'DESCRIPTOR' : _LEGDEFINITION,
  '__module__' : 'WebAPI.strategy_definition_2_pb2'
  # @@protoc_insertion_point(class_scope:strategy_definition_2.LegDefinition)
  })
_sym_db.RegisterMessage(LegDefinition)

NestedStrategy = _reflection.GeneratedProtocolMessageType('NestedStrategy', (_message.Message,), {
  'DESCRIPTOR' : _NESTEDSTRATEGY,
  '__module__' : 'WebAPI.strategy_definition_2_pb2'
  # @@protoc_insertion_point(class_scope:strategy_definition_2.NestedStrategy)
  })
_sym_db.RegisterMessage(NestedStrategy)

StrategyNodeDefinition = _reflection.GeneratedProtocolMessageType('StrategyNodeDefinition', (_message.Message,), {
  'DESCRIPTOR' : _STRATEGYNODEDEFINITION,
  '__module__' : 'WebAPI.strategy_definition_2_pb2'
  # @@protoc_insertion_point(class_scope:strategy_definition_2.StrategyNodeDefinition)
  })
_sym_db.RegisterMessage(StrategyNodeDefinition)


# @@protoc_insertion_point(module_scope)
