# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebAPI/user_attribute_2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WebAPI/user_attribute_2.proto',
  package='user_attribute_2',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dWebAPI/user_attribute_2.proto\x12\x10user_attribute_2\"=\n\rUserAttribute\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65leted\x18\x03 \x01(\x08\"\x90\x01\n\x14ModifyUserAttributes\x12\x16\n\x0e\x63hain_order_id\x18\x01 \x02(\t\x12\x12\n\naccount_id\x18\x02 \x02(\x11\x12\x38\n\x0fuser_attributes\x18\x03 \x03(\x0b\x32\x1f.user_attribute_2.UserAttribute\x12\x12\n\nis_checked\x18\x04 \x01(\x08\"G\n\x18ReadUserAttributeRequest\x12\x12\n\nrequest_id\x18\x01 \x02(\r\x12\x17\n\x0f\x61ttribute_names\x18\x02 \x03(\t\"\x80\x02\n\x17ReadUserAttributeResult\x12\x12\n\nrequest_id\x18\x01 \x02(\r\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12\x38\n\x0fuser_attributes\x18\x03 \x03(\x0b\x32\x1f.user_attribute_2.UserAttribute\x12\x14\n\x0ctext_message\x18\x04 \x01(\t\"l\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65\x12,\n(RESULT_CODE_REQUEST_RATE_LIMIT_VIOLATION\x10\x66\"j\n\x1aModifyUserAttributeRequest\x12\x12\n\nrequest_id\x18\x01 \x02(\r\x12\x38\n\x0fuser_attributes\x18\x02 \x03(\x0b\x32\x1f.user_attribute_2.UserAttribute\"\xf8\x01\n\x19ModifyUserAttributeResult\x12\x12\n\nrequest_id\x18\x01 \x02(\r\x12\x13\n\x0bresult_code\x18\x02 \x02(\r\x12\x14\n\x0ctext_message\x18\x03 \x01(\t\"\x9b\x01\n\nResultCode\x12\x17\n\x13RESULT_CODE_SUCCESS\x10\x00\x12\x17\n\x13RESULT_CODE_FAILURE\x10\x65\x12,\n(RESULT_CODE_REQUEST_RATE_LIMIT_VIOLATION\x10\x66\x12-\n)RESULT_CODE_STORAGE_SPACE_LIMIT_VIOLATION\x10g'
)



_READUSERATTRIBUTERESULT_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='user_attribute_2.ReadUserAttributeResult.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_FAILURE', index=1, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_REQUEST_RATE_LIMIT_VIOLATION', index=2, number=102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=483,
  serialized_end=591,
)
_sym_db.RegisterEnumDescriptor(_READUSERATTRIBUTERESULT_RESULTCODE)

_MODIFYUSERATTRIBUTERESULT_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='user_attribute_2.ModifyUserAttributeResult.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_FAILURE', index=1, number=101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_REQUEST_RATE_LIMIT_VIOLATION', index=2, number=102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_CODE_STORAGE_SPACE_LIMIT_VIOLATION', index=3, number=103,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=795,
  serialized_end=950,
)
_sym_db.RegisterEnumDescriptor(_MODIFYUSERATTRIBUTERESULT_RESULTCODE)


_USERATTRIBUTE = _descriptor.Descriptor(
  name='UserAttribute',
  full_name='user_attribute_2.UserAttribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='user_attribute_2.UserAttribute.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='user_attribute_2.UserAttribute.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='user_attribute_2.UserAttribute.deleted', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=112,
)


_MODIFYUSERATTRIBUTES = _descriptor.Descriptor(
  name='ModifyUserAttributes',
  full_name='user_attribute_2.ModifyUserAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain_order_id', full_name='user_attribute_2.ModifyUserAttributes.chain_order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='user_attribute_2.ModifyUserAttributes.account_id', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_attributes', full_name='user_attribute_2.ModifyUserAttributes.user_attributes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_checked', full_name='user_attribute_2.ModifyUserAttributes.is_checked', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=259,
)


_READUSERATTRIBUTEREQUEST = _descriptor.Descriptor(
  name='ReadUserAttributeRequest',
  full_name='user_attribute_2.ReadUserAttributeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='user_attribute_2.ReadUserAttributeRequest.request_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attribute_names', full_name='user_attribute_2.ReadUserAttributeRequest.attribute_names', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=332,
)


_READUSERATTRIBUTERESULT = _descriptor.Descriptor(
  name='ReadUserAttributeResult',
  full_name='user_attribute_2.ReadUserAttributeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='user_attribute_2.ReadUserAttributeResult.request_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='user_attribute_2.ReadUserAttributeResult.result_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_attributes', full_name='user_attribute_2.ReadUserAttributeResult.user_attributes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_message', full_name='user_attribute_2.ReadUserAttributeResult.text_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _READUSERATTRIBUTERESULT_RESULTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=591,
)


_MODIFYUSERATTRIBUTEREQUEST = _descriptor.Descriptor(
  name='ModifyUserAttributeRequest',
  full_name='user_attribute_2.ModifyUserAttributeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='user_attribute_2.ModifyUserAttributeRequest.request_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_attributes', full_name='user_attribute_2.ModifyUserAttributeRequest.user_attributes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=699,
)


_MODIFYUSERATTRIBUTERESULT = _descriptor.Descriptor(
  name='ModifyUserAttributeResult',
  full_name='user_attribute_2.ModifyUserAttributeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='user_attribute_2.ModifyUserAttributeResult.request_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='user_attribute_2.ModifyUserAttributeResult.result_code', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_message', full_name='user_attribute_2.ModifyUserAttributeResult.text_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODIFYUSERATTRIBUTERESULT_RESULTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=702,
  serialized_end=950,
)

_MODIFYUSERATTRIBUTES.fields_by_name['user_attributes'].message_type = _USERATTRIBUTE
_READUSERATTRIBUTERESULT.fields_by_name['user_attributes'].message_type = _USERATTRIBUTE
_READUSERATTRIBUTERESULT_RESULTCODE.containing_type = _READUSERATTRIBUTERESULT
_MODIFYUSERATTRIBUTEREQUEST.fields_by_name['user_attributes'].message_type = _USERATTRIBUTE
_MODIFYUSERATTRIBUTERESULT_RESULTCODE.containing_type = _MODIFYUSERATTRIBUTERESULT
DESCRIPTOR.message_types_by_name['UserAttribute'] = _USERATTRIBUTE
DESCRIPTOR.message_types_by_name['ModifyUserAttributes'] = _MODIFYUSERATTRIBUTES
DESCRIPTOR.message_types_by_name['ReadUserAttributeRequest'] = _READUSERATTRIBUTEREQUEST
DESCRIPTOR.message_types_by_name['ReadUserAttributeResult'] = _READUSERATTRIBUTERESULT
DESCRIPTOR.message_types_by_name['ModifyUserAttributeRequest'] = _MODIFYUSERATTRIBUTEREQUEST
DESCRIPTOR.message_types_by_name['ModifyUserAttributeResult'] = _MODIFYUSERATTRIBUTERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserAttribute = _reflection.GeneratedProtocolMessageType('UserAttribute', (_message.Message,), {
  'DESCRIPTOR' : _USERATTRIBUTE,
  '__module__' : 'WebAPI.user_attribute_2_pb2'
  # @@protoc_insertion_point(class_scope:user_attribute_2.UserAttribute)
  })
_sym_db.RegisterMessage(UserAttribute)

ModifyUserAttributes = _reflection.GeneratedProtocolMessageType('ModifyUserAttributes', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYUSERATTRIBUTES,
  '__module__' : 'WebAPI.user_attribute_2_pb2'
  # @@protoc_insertion_point(class_scope:user_attribute_2.ModifyUserAttributes)
  })
_sym_db.RegisterMessage(ModifyUserAttributes)

ReadUserAttributeRequest = _reflection.GeneratedProtocolMessageType('ReadUserAttributeRequest', (_message.Message,), {
  'DESCRIPTOR' : _READUSERATTRIBUTEREQUEST,
  '__module__' : 'WebAPI.user_attribute_2_pb2'
  # @@protoc_insertion_point(class_scope:user_attribute_2.ReadUserAttributeRequest)
  })
_sym_db.RegisterMessage(ReadUserAttributeRequest)

ReadUserAttributeResult = _reflection.GeneratedProtocolMessageType('ReadUserAttributeResult', (_message.Message,), {
  'DESCRIPTOR' : _READUSERATTRIBUTERESULT,
  '__module__' : 'WebAPI.user_attribute_2_pb2'
  # @@protoc_insertion_point(class_scope:user_attribute_2.ReadUserAttributeResult)
  })
_sym_db.RegisterMessage(ReadUserAttributeResult)

ModifyUserAttributeRequest = _reflection.GeneratedProtocolMessageType('ModifyUserAttributeRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYUSERATTRIBUTEREQUEST,
  '__module__' : 'WebAPI.user_attribute_2_pb2'
  # @@protoc_insertion_point(class_scope:user_attribute_2.ModifyUserAttributeRequest)
  })
_sym_db.RegisterMessage(ModifyUserAttributeRequest)

ModifyUserAttributeResult = _reflection.GeneratedProtocolMessageType('ModifyUserAttributeResult', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYUSERATTRIBUTERESULT,
  '__module__' : 'WebAPI.user_attribute_2_pb2'
  # @@protoc_insertion_point(class_scope:user_attribute_2.ModifyUserAttributeResult)
  })
_sym_db.RegisterMessage(ModifyUserAttributeResult)


# @@protoc_insertion_point(module_scope)
